// ─────────────────────────────────────────────────────────────────────────────
// SimchaKit V3 — api/reset-demo.js
// Resets the demo event to baseline Simpsons data.
// V3 schema: all collection rows use { id, event_id, data: jsonb }
// ─────────────────────────────────────────────────────────────────────────────

import { createClient } from "@supabase/supabase-js";

const DEMO_EVENT_ID   = "440a8b9e-e92e-4ad6-b352-41965bd8383b";
const DEMO_USER_EMAIL = "demo@simchakit.app";

const COLLECTIONS = [
  "households", "people", "expenses", "vendors", "tasks",
  "prep", "tables", "gifts", "favors", "ceremony_roles",
  "audit_log", "dayof",
];

const SEED = {
  "adminConfig": {
    "name": "Bart Simpson's Bar Mitzvah",
    "type": "bar-mitzvah",
    "rsvpUrl": "https://bartsbarmi.example-rsvp.com",
    "rsvpDeadline": "2027-09-15",
    "cateringStyle": "plated",
    "notes": "Venue requires final headcount 72 hours before event. Must notify caterer of all dietary restrictions by Oct 9.",
    "accomHotelName": "Springfield Grand Hotel",
    "accomGroupCode": "SIMPSON27",
    "accomCutoffDate": "2027-09-30",
    "accomPhone": "555-636-4636",
    "accomWebsite": "https://springfieldgrand.example.com",
    "timeline": [
      {
        "id": "tl_01",
        "icon": "\ud83d\udcf8",
        "title": "Photo Session",
        "startDate": "2027-10-15",
        "startTime": "12:00",
        "endDate": "2027-10-15",
        "endTime": "14:30",
        "venue": "Temple Beth Springfield",
        "notes": "",
        "isMainEvent": false
      },
      {
        "id": "tl_02",
        "icon": "\ud83c\udf7d\ufe0f",
        "title": "Friday Night Dinner",
        "startDate": "2027-10-15",
        "startTime": "19:00",
        "endDate": "",
        "endTime": "",
        "venue": "The Springfield Grill",
        "notes": "Out of towners, family, close friends",
        "isMainEvent": false
      },
      {
        "id": "tl_03",
        "icon": "\ud83d\udd4d",
        "title": "Bar Mitzvah Service",
        "startDate": "2027-10-16",
        "startTime": "09:30",
        "endDate": "",
        "endTime": "",
        "venue": "Temple Beth Springfield",
        "notes": "",
        "isMainEvent": true
      },
      {
        "id": "tl_04",
        "icon": "\ud83c\udf55",
        "title": "Kiddush Luncheon",
        "startDate": "2027-10-16",
        "startTime": "12:00",
        "endDate": "",
        "endTime": "",
        "venue": "Temple Beth Springfield",
        "notes": "",
        "isMainEvent": false
      },
      {
        "id": "tl_05",
        "icon": "\ud83c\udf89",
        "title": "Evening Party",
        "startDate": "2027-10-16",
        "startTime": "19:00",
        "endDate": "2027-10-16",
        "endTime": "23:00",
        "venue": "Springfield Country Club",
        "notes": "",
        "isMainEvent": false
      }
    ],
    "theme": {
      "name": "Eating My Shorts",
      "icon": "",
      "palette": "slate"
    },
    "groups": [
      "Family",
      "Friends",
      "Class",
      "Other"
    ],
    "mealChoices": [
      "Chicken",
      "Fish",
      "Vegetarian",
      "Kids Meal",
      "Kosher"
    ],
    "shirtSizes": [
      "YS | Youth Small",
      "YM | Youth Medium",
      "YL | Youth Large",
      "AS | Adult Small",
      "AM | Adult Medium",
      "AL | Adult Large",
      "XL | Adult XL",
      "XXL | Adult XXL"
    ],
    "visibleTabs": [],
    "hotelBlocks": [
      {
        "id": "hb_migrated",
        "name": "Springfield Grand Hotel",
        "groupCode": "SIMPSON27",
        "cutoffDate": "2027-09-30",
        "phone": "555-636-4636",
        "website": "https://springfieldgrand.example.com"
      }
    ],
    "rabbi": {
      "name": "Rabbi Hyman Krustofsky",
      "phone": "555-636-7878",
      "email": "rabbi.krustofsky@bethspringfield.example.org"
    },
    "cantor": {
      "name": "Cantor Miriam Goldman",
      "phone": "555-636-7879",
      "email": "cantor.goldman@bethspringfield.example.org"
    },
    "tutor": {
      "name": "David Cohen",
      "phone": "555-636-7880",
      "email": "dcohen@hebrewtutors.example.com"
    }
  },
  "households": [
    {
      "id": "h001",
      "name": "Simpson Family",
      "formalName": "Mr. and Mrs. Homer Simpson",
      "group": "Family",
      "status": "RSVP Yes",
      "address1": "742 Evergreen Terrace",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 2,
      "attendingAdults": 2,
      "attendingKids": 2,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-10",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Dietary: Lisa Simpson \u2014 vegetarian. No meat of any kind. Members: Homer Simpson, Marge Simpson, Bart Simpson, Lisa Simpson. Contact: homer@powerplant.example.com, 555-636-0001",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h002",
      "name": "Flanders Family",
      "formalName": "Mr. Ned Flanders",
      "group": "Family",
      "status": "RSVP Yes",
      "address1": "744 Evergreen Terrace",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 1,
      "kids": 2,
      "attendingAdults": 1,
      "attendingKids": 2,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-05",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Dietary: Ned Flanders \u2014 strictly kosher. Rod and Todd also kosher.",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h003",
      "name": "Bouvier Grandma",
      "formalName": "Mrs. Jacqueline Bouvier",
      "group": "Family",
      "status": "RSVP Yes",
      "address1": "430 Spinster Lane",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 1,
      "kids": 0,
      "attendingAdults": 1,
      "attendingKids": 0,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-01",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Members: Jacqueline Bouvier. Marge's mother. Contact: 555-636-0003",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h004",
      "name": "Bouvier Sisters",
      "formalName": "Ms. Patty Bouvier and Ms. Selma Bouvier",
      "group": "Family",
      "status": "RSVP Yes",
      "address1": "1002 Elm Street",
      "address2": "Apt 4B",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 0,
      "attendingAdults": 2,
      "attendingKids": 0,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-08",
      "outOfTown": true,
      "accomNotified": true,
      "notes": "Members: Patty Bouvier, Selma Bouvier. Marge's sisters. Contact: patty@dmv.example.com, 555-636-0004",
      "inviteDate": "2027-05-01",
      "accomBooked": true,
      "accomCheckIn": "2027-10-15",
      "accomCheckOut": "2027-10-17",
      "eventSection": "",
      "invitedSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h005",
      "name": "Terwilliger Family",
      "formalName": "Mr. and Mrs. Robert Terwilliger Sr.",
      "group": "Family",
      "status": "RSVP Yes",
      "address1": "45 Magnolia Lane",
      "address2": "",
      "city": "Shelbyville",
      "stateProvince": "IL",
      "postalCode": "62702",
      "country": "United States",
      "adults": 2,
      "kids": 0,
      "attendingAdults": 2,
      "attendingKids": 0,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-07-01",
      "outOfTown": true,
      "accomNotified": true,
      "notes": "Members: Robert Terwilliger Sr., Judith Terwilliger. Out of town \u2014 Shelbyville. Contact: 555-637-0005",
      "inviteDate": "2027-05-01",
      "accomBooked": true,
      "accomCheckIn": "2027-10-15",
      "accomCheckOut": "2027-10-17",
      "eventSection": "",
      "invitedSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h006",
      "name": "Van Houten Family",
      "formalName": "Mr. and Mrs. Kirk Van Houten",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "219 Fisgard Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 1,
      "attendingAdults": 2,
      "attendingKids": 1,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-20",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Members: Kirk Van Houten, Luann Van Houten, Milhouse Van Houten. Contact: kirk@vanhouten.example.com, 555-636-0006",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h007",
      "name": "Wiggum Family",
      "formalName": "Chief and Mrs. Clancy Wiggum",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "137 Beaumont Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 1,
      "attendingAdults": 2,
      "attendingKids": 1,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-07-10",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Dietary: Ralph Wiggum \u2014 severe nut allergy (peanuts and tree nuts). Notify caterer.",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h008",
      "name": "Hibbert Family",
      "formalName": "Dr. and Mrs. Julius Hibbert",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "156 Elm Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 2,
      "attendingAdults": 2,
      "attendingKids": 2,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-15",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Dietary: Jules Hibbert \u2014 kosher only. Contact: dr.hibbert@springfieldmed.example.com, 555-636-0008",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h009",
      "name": "Carlson & Powell",
      "formalName": "Mr. Carl Carlson and Ms. Lenny Powell",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "800 Industrial Way",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 0,
      "attendingAdults": 2,
      "attendingKids": 0,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-08-01",
      "outOfTown": true,
      "accomNotified": true,
      "notes": "Members: Carl Carlson, Lenny Powell. Homer's coworkers. Contact: carl@powerplant.example.com, 555-636-0009",
      "inviteDate": "2027-05-01",
      "accomBooked": false,
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h010",
      "name": "Lovejoy Family",
      "formalName": "Reverend and Mrs. Timothy Lovejoy",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "100 Church Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 1,
      "attendingAdults": 2,
      "attendingKids": 1,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-25",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Dietary: Helen Lovejoy \u2014 gluten free. Members: Timothy Lovejoy, Helen Lovejoy, Jessica Lovejoy. Contact: rev@springfieldchurch.example.com, 555-636-0010",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h011",
      "name": "Quimby Family",
      "formalName": "Mayor and Mrs. Joseph Quimby",
      "group": "Friends",
      "status": "RSVP No",
      "address1": "1 Municipal Plaza",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 0,
      "attendingAdults": 0,
      "attendingKids": 0,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-07-20",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Members: Joseph Quimby, Martha Quimby. Prior engagement at city hall. Contact: mayor@springfield.example.com, 555-636-0011",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h012",
      "name": "Prince Family",
      "formalName": "Mr. and Mrs. Martin Prince Sr.",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "22 Oak Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 1,
      "attendingAdults": 2,
      "attendingKids": 1,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-06-30",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Members: Martin Prince Sr., Mrs. Prince, Martin Prince Jr. Contact: martin.sr@springfield.example.com, 555-636-0012",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h013",
      "name": "Skinner Family",
      "formalName": "Principal and Mrs. Seymour Skinner",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "22 Oak Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 0,
      "attendingAdults": 2,
      "attendingKids": 0,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-07-05",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Members: Seymour Skinner, Agnes Skinner. Bart's principal. Contact: principal@springfieldelementary.example.com, 555-636-0013",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h014",
      "name": "Burns & Smithers",
      "formalName": "Mr. C. Montgomery Burns and Mr. Waylon Smithers",
      "group": "Friends",
      "status": "Pending",
      "address1": "1000 Burns Manor",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 2,
      "kids": 0,
      "attendingAdults": null,
      "attendingKids": null,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": null,
      "outOfTown": true,
      "accomNotified": false,
      "notes": "Members: C. Montgomery Burns, Waylon Smithers. Homer's employer. Contact: smithers@burnscorp.example.com, 555-636-0014",
      "inviteDate": "2027-05-01",
      "accomBooked": false,
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h015",
      "name": "Muntz Family",
      "formalName": "Ms. Gloria Muntz",
      "group": "Friends",
      "status": "RSVP Yes",
      "address1": "1000 Poverty Lane",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 1,
      "kids": 1,
      "attendingAdults": 1,
      "attendingKids": 1,
      "saveTheDateSent": true,
      "inviteSent": true,
      "rsvpDate": "2027-08-10",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Members: Gloria Muntz, Nelson Muntz. Contact: 555-636-0015",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h016",
      "name": "Sherri Mackleberry",
      "formalName": "Miss Sherri Mackleberry",
      "group": "Class",
      "status": "RSVP Yes",
      "address1": "88 Chestnut Drive",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": 0,
      "attendingKids": 1,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-07-15",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Contact: parent.mackleberry@springfield.example.com, 555-636-0016",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h017",
      "name": "Terri Mackleberry",
      "formalName": "Miss Terri Mackleberry",
      "group": "Class",
      "status": "RSVP Yes",
      "address1": "88 Chestnut Drive",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": 0,
      "attendingKids": 1,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-07-15",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Twin sister of Sherri. Contact: parent.mackleberry@springfield.example.com, 555-636-0016",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h018",
      "name": "Wendell Borton",
      "formalName": "Mr. Wendell Borton",
      "group": "Class",
      "status": "RSVP Yes",
      "address1": "55 Willow Way",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": 0,
      "attendingKids": 1,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-08-05",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Contact: borton@springfield.example.com, 555-636-0018",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h019",
      "name": "Database",
      "formalName": "Mr. Database",
      "group": "Class",
      "status": "RSVP Yes",
      "address1": "14 Binary Lane",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": 0,
      "attendingKids": 1,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-07-28",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Contact: database@springfield.example.com, 555-636-0019",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h020",
      "name": "Jimbo Jones",
      "formalName": "Mr. Jimbo Jones",
      "group": "Class",
      "status": "Maybe",
      "address1": "77 Trouble Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": null,
      "attendingKids": null,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": null,
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Contact: 555-636-0020. Will confirm after summer.",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h021",
      "name": "Kearney Zzyzwicz",
      "formalName": "Mr. Kearney Zzyzwicz",
      "group": "Class",
      "status": "RSVP No",
      "address1": "99 Dead End Road",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": 0,
      "attendingKids": 0,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-09-01",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Contact: 555-636-0021. Has a son of his own to look after.",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h022",
      "name": "Janey Powell",
      "formalName": "Miss Janey Powell",
      "group": "Class",
      "status": "RSVP Yes",
      "address1": "33 Maple Avenue",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": 0,
      "attendingKids": 1,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-07-22",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Dietary: Janey Powell \u2014 kosher preferred, will eat vegetarian if not certified.",
      "inviteDate": "2027-05-15",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h023",
      "name": "Richard",
      "formalName": "Mr. Richard",
      "group": "Class",
      "status": "Pending",
      "address1": "",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "",
      "country": "United States",
      "adults": 0,
      "kids": 1,
      "attendingAdults": null,
      "attendingKids": null,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": null,
      "outOfTown": false,
      "accomNotified": false,
      "notes": "No address on file. Contact: 555-636-0023",
      "inviteDate": "2027-04-01",
      "eventSection": "",
      "invitedSections": [
        "tl_05"
      ]
    },
    {
      "id": "h024",
      "name": "Rabbi Krustofsky",
      "formalName": "Rabbi Hyman Krustofsky",
      "group": "Other",
      "status": "RSVP Yes",
      "address1": "100 Temple Way",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 1,
      "kids": 0,
      "attendingAdults": 1,
      "attendingKids": 0,
      "saveTheDateSent": false,
      "inviteSent": true,
      "rsvpDate": "2027-05-20",
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Officiant. Contact: rabbi@springfieldsynagogue.example.com, 555-636-0024",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "h025",
      "name": "Hutz, Lionel",
      "formalName": "Mr. Lionel Hutz",
      "group": "Other",
      "status": "Invited",
      "address1": "555 Court Street",
      "address2": "",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "adults": 1,
      "kids": 0,
      "attendingAdults": null,
      "attendingKids": null,
      "saveTheDateSent": true,
      "inviteSent": false,
      "rsvpDate": null,
      "outOfTown": false,
      "accomNotified": false,
      "notes": "Family attorney. Invite not yet sent \u2014 confirm address. Contact: lionel.hutz@caseclosed.example.com, 555-636-0025",
      "inviteDate": "2027-05-01",
      "eventSection": "",
      "invitedSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    }
  ],
  "people": [
    {
      "id": "p001",
      "householdId": "h001",
      "firstName": "Homer",
      "lastName": "Simpson",
      "name": "Homer Simpson",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl001",
      "shirtSize": "XXL | Adult XXL",
      "pantSize": "AL | Adult Large",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p002",
      "householdId": "h001",
      "firstName": "Marge",
      "lastName": "Simpson",
      "name": "Marge Simpson",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl001",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p003",
      "householdId": "h001",
      "firstName": "Bart",
      "lastName": "Simpson",
      "name": "Bart Simpson",
      "title": "",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YM | Youth Medium",
      "pantSize": "YM | Youth Medium",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "Bar Mitzvah boy",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p004",
      "householdId": "h001",
      "firstName": "Lisa",
      "lastName": "Simpson",
      "name": "Lisa Simpson",
      "title": "Miss",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Vegetarian",
      "kosher": false,
      "dietary": "Vegetarian \u2014 no meat of any kind",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p005",
      "householdId": "h002",
      "firstName": "Ned",
      "lastName": "Flanders",
      "name": "Ned Flanders",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl001",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Kosher",
      "kosher": true,
      "dietary": "Strictly kosher",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p006",
      "householdId": "h002",
      "firstName": "Rod",
      "lastName": "Flanders",
      "name": "Rod Flanders",
      "title": "",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kosher",
      "kosher": true,
      "dietary": "Strictly kosher",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p007",
      "householdId": "h002",
      "firstName": "Todd",
      "lastName": "Flanders",
      "name": "Todd Flanders",
      "title": "",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kosher",
      "kosher": true,
      "dietary": "Strictly kosher",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p008",
      "householdId": "h003",
      "firstName": "Jacqueline",
      "lastName": "Bouvier",
      "name": "Jacqueline Bouvier",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl001",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p009",
      "householdId": "h004",
      "firstName": "Patty",
      "lastName": "Bouvier",
      "name": "Patty Bouvier",
      "title": "Ms.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl001",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p010",
      "householdId": "h004",
      "firstName": "Selma",
      "lastName": "Bouvier",
      "name": "Selma Bouvier",
      "title": "Ms.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl001",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p011",
      "householdId": "h005",
      "firstName": "Robert",
      "lastName": "Terwilliger Sr.",
      "name": "Robert Terwilliger Sr.",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AL | Adult Large",
      "pantSize": "AL | Adult Large",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p012",
      "householdId": "h005",
      "firstName": "Judith",
      "lastName": "Terwilliger",
      "name": "Judith Terwilliger",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_01",
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p013",
      "householdId": "h006",
      "firstName": "Kirk",
      "lastName": "Van Houten",
      "name": "Kirk Van Houten",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl002",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p014",
      "householdId": "h006",
      "firstName": "Luann",
      "lastName": "Van Houten",
      "name": "Luann Van Houten",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl002",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p015",
      "householdId": "h006",
      "firstName": "Milhouse",
      "lastName": "Van Houten",
      "name": "Milhouse Van Houten",
      "title": "",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p016",
      "householdId": "h007",
      "firstName": "Clancy",
      "lastName": "Wiggum",
      "name": "Clancy Wiggum",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl002",
      "shirtSize": "XL | Adult XL",
      "pantSize": "XL | Adult XL",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p017",
      "householdId": "h007",
      "firstName": "Sarah",
      "lastName": "Wiggum",
      "name": "Sarah Wiggum",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl002",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p018",
      "householdId": "h007",
      "firstName": "Ralph",
      "lastName": "Wiggum",
      "name": "Ralph Wiggum",
      "title": "",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YL | Youth Large",
      "pantSize": "YL | Youth Large",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "Severe nut allergy \u2014 peanuts and tree nuts. Alert caterer.",
      "notes": "",
      "attendingSections": [
        "tl_02",
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p019",
      "householdId": "h008",
      "firstName": "Julius",
      "lastName": "Hibbert",
      "name": "Julius Hibbert",
      "title": "Dr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl002",
      "shirtSize": "AL | Adult Large",
      "pantSize": "AL | Adult Large",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p020",
      "householdId": "h008",
      "firstName": "Bernice",
      "lastName": "Hibbert",
      "name": "Bernice Hibbert",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl002",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p021",
      "householdId": "h008",
      "firstName": "Janey",
      "lastName": "Hibbert",
      "name": "Janey Hibbert",
      "title": "Miss",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p022",
      "householdId": "h008",
      "firstName": "Jules",
      "lastName": "Hibbert",
      "name": "Jules Hibbert",
      "title": "Mr.",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YM | Youth Medium",
      "pantSize": "YM | Youth Medium",
      "mealChoice": "Kosher",
      "kosher": true,
      "dietary": "Kosher only",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p023",
      "householdId": "h009",
      "firstName": "Carl",
      "lastName": "Carlson",
      "name": "Carl Carlson",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AL | Adult Large",
      "pantSize": "AL | Adult Large",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p024",
      "householdId": "h009",
      "firstName": "Lenny",
      "lastName": "Powell",
      "name": "Lenny Powell",
      "title": "Ms.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Vegetarian",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p025",
      "householdId": "h010",
      "firstName": "Timothy",
      "lastName": "Lovejoy",
      "name": "Timothy Lovejoy",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p026",
      "householdId": "h010",
      "firstName": "Helen",
      "lastName": "Lovejoy",
      "name": "Helen Lovejoy",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "Gluten free \u2014 celiac disease. No wheat, barley, or rye.",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p027",
      "householdId": "h010",
      "firstName": "Jessica",
      "lastName": "Lovejoy",
      "name": "Jessica Lovejoy",
      "title": "Miss",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p028",
      "householdId": "h011",
      "firstName": "Joseph",
      "lastName": "Quimby",
      "name": "Joseph Quimby",
      "title": "Mr.",
      "isChild": false,
      "isAttending": false,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": []
    },
    {
      "id": "p029",
      "householdId": "h011",
      "firstName": "Martha",
      "lastName": "Quimby",
      "name": "Martha Quimby",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": false,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": []
    },
    {
      "id": "p030",
      "householdId": "h012",
      "firstName": "Martin",
      "lastName": "Prince Sr.",
      "name": "Martin Prince Sr.",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p031",
      "householdId": "h012",
      "firstName": "Martha",
      "lastName": "Prince",
      "name": "Martha Prince",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p032",
      "householdId": "h012",
      "firstName": "Martin",
      "lastName": "Prince Jr.",
      "name": "Martin Prince Jr.",
      "title": "Mr.",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p033",
      "householdId": "h013",
      "firstName": "Seymour",
      "lastName": "Skinner",
      "name": "Seymour Skinner",
      "title": "Mr.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p034",
      "householdId": "h013",
      "firstName": "Agnes",
      "lastName": "Skinner",
      "name": "Agnes Skinner",
      "title": "Mrs.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Fish",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p035",
      "householdId": "h014",
      "firstName": "C. Montgomery",
      "lastName": "Burns",
      "name": "C. Montgomery Burns",
      "title": "Mr.",
      "isChild": false,
      "isAttending": null,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": []
    },
    {
      "id": "p036",
      "householdId": "h014",
      "firstName": "Waylon",
      "lastName": "Smithers",
      "name": "Waylon Smithers",
      "title": "Mr.",
      "isChild": false,
      "isAttending": null,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": []
    },
    {
      "id": "p037",
      "householdId": "h015",
      "firstName": "Gloria",
      "lastName": "Muntz",
      "name": "Gloria Muntz",
      "title": "Ms.",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AS | Adult Small",
      "pantSize": "AS | Adult Small",
      "mealChoice": "Chicken",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p038",
      "householdId": "h015",
      "firstName": "Nelson",
      "lastName": "Muntz",
      "name": "Nelson Muntz",
      "title": "",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YM | Youth Medium",
      "pantSize": "YM | Youth Medium",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p039",
      "householdId": "h016",
      "firstName": "Sherri",
      "lastName": "Mackleberry",
      "name": "Sherri Mackleberry",
      "title": "Miss",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_05"
      ]
    },
    {
      "id": "p040",
      "householdId": "h017",
      "firstName": "Terri",
      "lastName": "Mackleberry",
      "name": "Terri Mackleberry",
      "title": "Miss",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_05"
      ]
    },
    {
      "id": "p041",
      "householdId": "h018",
      "firstName": "Wendell",
      "lastName": "Borton",
      "name": "Wendell Borton",
      "title": "Mr.",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YM | Youth Medium",
      "pantSize": "YM | Youth Medium",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_05"
      ]
    },
    {
      "id": "p042",
      "householdId": "h019",
      "firstName": "Database",
      "lastName": "",
      "name": "Database",
      "title": "Mr.",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kids Meal",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_05"
      ]
    },
    {
      "id": "p043",
      "householdId": "h020",
      "firstName": "Jimbo",
      "lastName": "Jones",
      "name": "Jimbo Jones",
      "title": "Mr.",
      "isChild": true,
      "isAttending": null,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": []
    },
    {
      "id": "p044",
      "householdId": "h021",
      "firstName": "Kearney",
      "lastName": "Zzyzwicz",
      "name": "Kearney Zzyzwicz",
      "title": "Mr.",
      "isChild": true,
      "isAttending": false,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": []
    },
    {
      "id": "p045",
      "householdId": "h022",
      "firstName": "Janey",
      "lastName": "Powell",
      "name": "Janey Powell",
      "title": "Miss",
      "isChild": true,
      "isAttending": true,
      "tableId": "tbl004",
      "shirtSize": "YS | Youth Small",
      "pantSize": "YS | Youth Small",
      "mealChoice": "Kosher",
      "kosher": true,
      "dietary": "Kosher preferred, vegetarian if not certified",
      "notes": "",
      "attendingSections": [
        "tl_05"
      ]
    },
    {
      "id": "p046",
      "householdId": "h023",
      "firstName": "Hyman",
      "lastName": "Krustofsky",
      "name": "Hyman Krustofsky",
      "title": "Rabbi",
      "isChild": false,
      "isAttending": true,
      "tableId": "tbl003",
      "shirtSize": "AM | Adult Medium",
      "pantSize": "AM | Adult Medium",
      "mealChoice": "Kosher",
      "kosher": true,
      "dietary": "Strictly kosher",
      "notes": "Officiant",
      "attendingSections": []
    },
    {
      "id": "p047",
      "householdId": "h024",
      "firstName": "Lionel",
      "lastName": "Hutz",
      "name": "Lionel Hutz",
      "title": "Mr.",
      "isChild": false,
      "isAttending": null,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "",
      "attendingSections": [
        "tl_03",
        "tl_04",
        "tl_05"
      ]
    },
    {
      "id": "p048",
      "householdId": "h025",
      "firstName": "Nick",
      "lastName": "Riviera",
      "name": "Nick Riviera",
      "title": "Dr.",
      "isChild": false,
      "isAttending": null,
      "tableId": null,
      "shirtSize": "",
      "pantSize": "",
      "mealChoice": "",
      "kosher": false,
      "dietary": "",
      "notes": "Hi everybody!",
      "attendingSections": []
    }
  ],
  "expenses": [
    {
      "id": "e001",
      "description": "Springfield Country Club \u2014 Room Fee",
      "category": "Venue",
      "vendor": "Springfield Country Club",
      "vendorId": "v001",
      "amount": "3500",
      "budgeted": "3500",
      "date": "2027-01-15",
      "dueDate": "",
      "paid": true,
      "notes": "Non-refundable. Event #BAR2027.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e002",
      "description": "Temple Beth Springfield \u2014 Tuition Deposit",
      "category": "Venue",
      "vendor": "Temple Beth Springfield",
      "vendorId": "v002",
      "amount": "500",
      "budgeted": "1000",
      "date": "2026-11-01",
      "dueDate": "",
      "paid": true,
      "notes": "50% deposit. Balance due Jul 2027.",
      "eventSection": "Bar Mitzvah Service"
    },
    {
      "id": "e003",
      "description": "Temple Beth Springfield \u2014 Tuition Balance",
      "category": "Venue",
      "vendor": "Temple Beth Springfield",
      "vendorId": "v002",
      "amount": "500",
      "budgeted": "500",
      "date": "",
      "dueDate": "2027-07-01",
      "paid": false,
      "notes": "Due one year prior to simhah.",
      "eventSection": "Bar Mitzvah Service"
    },
    {
      "id": "e004",
      "description": "Temple Beth Springfield \u2014 Kiddush Sponsorship",
      "category": "Catering",
      "vendor": "Temple Beth Springfield",
      "vendorId": "v002",
      "amount": "800",
      "budgeted": "800",
      "date": "",
      "dueDate": "2027-07-16",
      "paid": false,
      "notes": "Due three months prior.",
      "eventSection": "Kiddush Luncheon"
    },
    {
      "id": "e005",
      "description": "Shelbyville Snapshots \u2014 Retainer",
      "category": "Photography/Video",
      "vendor": "Shelbyville Snapshots",
      "vendorId": "v003",
      "amount": "1400",
      "budgeted": "4200",
      "date": "2027-01-20",
      "dueDate": "",
      "paid": true,
      "notes": "Non-refundable booking retainer.",
      "eventSection": ""
    },
    {
      "id": "e006",
      "description": "Shelbyville Snapshots \u2014 Second Payment",
      "category": "Photography/Video",
      "vendor": "Shelbyville Snapshots",
      "vendorId": "v003",
      "amount": "1400",
      "budgeted": "",
      "date": "",
      "dueDate": "2027-10-02",
      "paid": false,
      "notes": "Due 14 days before event.",
      "eventSection": ""
    },
    {
      "id": "e007",
      "description": "Shelbyville Snapshots \u2014 Final Payment",
      "category": "Photography/Video",
      "vendor": "Shelbyville Snapshots",
      "vendorId": "v003",
      "amount": "1400",
      "budgeted": "",
      "date": "",
      "dueDate": "2027-12-01",
      "paid": false,
      "notes": "Due when photo gallery is delivered.",
      "eventSection": ""
    },
    {
      "id": "e008",
      "description": "DJ Krusty Spins \u2014 Retainer",
      "category": "DJ/Entertainment",
      "vendor": "DJ Krusty Spins",
      "vendorId": "v004",
      "amount": "1500",
      "budgeted": "8500",
      "date": "2027-01-20",
      "dueDate": "",
      "paid": true,
      "notes": "Non-refundable.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e009",
      "description": "DJ Krusty Spins \u2014 Balance",
      "category": "DJ/Entertainment",
      "vendor": "DJ Krusty Spins",
      "vendorId": "v004",
      "amount": "7000",
      "budgeted": "",
      "date": "",
      "dueDate": "2027-10-09",
      "paid": false,
      "notes": "Due 7 days before event.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e010",
      "description": "Bouvier Event Design \u2014 Retainer",
      "category": "Florals/Decor",
      "vendor": "Bouvier Event Design",
      "vendorId": "v005",
      "amount": "1875",
      "budgeted": "3750",
      "date": "2027-02-01",
      "dueDate": "",
      "paid": true,
      "notes": "50% retainer.",
      "eventSection": ""
    },
    {
      "id": "e011",
      "description": "Bouvier Event Design \u2014 Balance",
      "category": "Florals/Decor",
      "vendor": "Bouvier Event Design",
      "vendorId": "v005",
      "amount": "1875",
      "budgeted": "",
      "date": "",
      "dueDate": "2027-09-16",
      "paid": false,
      "notes": "Due 30 days before event.",
      "eventSection": ""
    },
    {
      "id": "e012",
      "description": "Springfield Country Club \u2014 Catering",
      "category": "Catering",
      "vendor": "Springfield Country Club",
      "vendorId": "v001",
      "amount": "8500",
      "budgeted": "9000",
      "date": "",
      "dueDate": "2027-10-09",
      "paid": false,
      "notes": "Per-head estimate based on 80 guests. Final invoice after event.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e013",
      "description": "Party Favors \u2014 Donut-themed sweatshirts",
      "category": "Party Favors",
      "vendor": "",
      "vendorId": "",
      "amount": "1200",
      "budgeted": "1200",
      "date": "",
      "dueDate": "2027-09-01",
      "paid": false,
      "notes": "Custom printed. Order 8 weeks before event.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e014",
      "description": "Invitations and Stationery",
      "category": "Invitations/Stationery",
      "vendor": "",
      "vendorId": "",
      "amount": "650",
      "budgeted": "700",
      "date": "2027-04-15",
      "dueDate": "",
      "paid": true,
      "notes": "Design, print, and postage.",
      "eventSection": ""
    },
    {
      "id": "e015",
      "description": "Kippot \u2014 Temple Sisterhood",
      "category": "Other",
      "vendor": "Temple Beth Springfield",
      "vendorId": "v002",
      "amount": "180",
      "budgeted": "200",
      "date": "",
      "dueDate": "2027-09-15",
      "paid": false,
      "notes": "Approx 40 kippot needed.",
      "eventSection": "Bar Mitzvah Service"
    },
    {
      "id": "e016",
      "description": "Hair and Makeup \u2014 Marge Simpson",
      "category": "Hair/Makeup",
      "vendor": "",
      "vendorId": "",
      "amount": "350",
      "budgeted": "400",
      "date": "",
      "dueDate": "2027-10-15",
      "paid": false,
      "notes": "Trial appointment booked for Sep 1.",
      "eventSection": ""
    },
    {
      "id": "e017",
      "description": "Springfield Florist \u2014 Centerpieces Quote",
      "category": "Florals/Decor",
      "vendor": "Springfield Florist",
      "vendorId": "v006",
      "amount": "1200",
      "budgeted": "1000",
      "date": "",
      "dueDate": "2027-09-01",
      "paid": false,
      "notes": "Quote received, over budget \u2014 negotiating.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e016",
      "description": "Gratuity \u2014 Shelbyville Snapshots",
      "category": "Gratuities & Tips",
      "vendor": "Shelbyville Snapshots",
      "vendorId": "v003",
      "amount": "420",
      "budgeted": "420",
      "date": "",
      "dueDate": "2027-10-16",
      "paid": false,
      "notes": "20% gratuity on $2,100 (day-of services). Pay in cash on the day.",
      "eventSection": ""
    },
    {
      "id": "e017",
      "description": "Gratuity \u2014 DJ Krusty Spins",
      "category": "Gratuities & Tips",
      "vendor": "DJ Krusty Spins",
      "vendorId": "v004",
      "amount": "850",
      "budgeted": "850",
      "date": "",
      "dueDate": "2027-10-16",
      "paid": false,
      "notes": "10% gratuity on $8,500 package. Venmo or cash.",
      "eventSection": "Evening Party"
    },
    {
      "id": "e018",
      "description": "Gratuity \u2014 Springfield Country Club catering staff",
      "category": "Gratuities & Tips",
      "vendor": "Springfield Country Club",
      "vendorId": "v001",
      "amount": "1200",
      "budgeted": "1200",
      "date": "",
      "dueDate": "2027-10-16",
      "paid": false,
      "notes": "Approximately 15% on catering. Confirm with coordinator.",
      "eventSection": "Evening Party"
    }
  ],
  "vendors": [
    {
      "id": "v001",
      "name": "Springfield Country Club",
      "type": "Venue",
      "status": "Paid in Full",
      "contractAmt": "3500",
      "phone": "555-636-4000",
      "email": "events@springfieldcc.example.com",
      "address1": "1 Country Club Drive",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "notes": "Ballroom rental for evening party. 150 guest capacity. In-house catering. Event #BAR2027.",
      "milestones": [
        {
          "id": "m001",
          "title": "Final headcount due",
          "date": "2027-10-09",
          "notes": "72 hours prior to event",
          "done": false
        },
        {
          "id": "m002",
          "title": "Menu selection deadline",
          "date": "2027-09-01",
          "notes": "",
          "done": false
        }
      ],
      "contactName": "Lenny Leonard"
    },
    {
      "id": "v002",
      "name": "Temple Beth Springfield",
      "type": "Venue",
      "status": "Deposit Paid",
      "contractAmt": "1800",
      "phone": "555-636-5000",
      "email": "rabbi@springfieldsynagogue.example.com",
      "address1": "100 Temple Way",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "notes": "Bar Mitzvah service Oct 16. Kiddush luncheon following service. Tuition: $1,000 ($500 deposit paid). Kiddush sponsorship: $800.",
      "milestones": [
        {
          "id": "m003",
          "title": "Tuition balance due",
          "date": "2027-07-01",
          "notes": "",
          "done": false
        },
        {
          "id": "m004",
          "title": "Final rehearsal",
          "date": "2027-10-09",
          "notes": "4:00-6:00 PM",
          "done": false
        }
      ],
      "contactName": "Rabbi Hyman Krustofsky"
    },
    {
      "id": "v003",
      "name": "Shelbyville Snapshots",
      "type": "Photographer",
      "status": "Deposit Paid",
      "contractAmt": "4200",
      "phone": "555-636-6000",
      "email": "sanjay@shelbyvillesnaps.example.com",
      "address1": "200 Camera Lane",
      "city": "Shelbyville",
      "stateProvince": "IL",
      "postalCode": "62702",
      "country": "United States",
      "notes": "Full day coverage. 6-hour party + temple session. 750-1,500 digital images, full rights. Must feed photographer.",
      "milestones": [
        {
          "id": "m005",
          "title": "Second payment due",
          "date": "2027-10-02",
          "notes": "14 days before event",
          "done": false
        },
        {
          "id": "m006",
          "title": "Shot list deadline",
          "date": "2027-09-15",
          "notes": "",
          "done": false
        }
      ],
      "contactName": "Sanjay Nahasapeemapetilon"
    },
    {
      "id": "v004",
      "name": "DJ Krusty Spins",
      "type": "DJ/Band",
      "status": "Deposit Paid",
      "contractAmt": "8500",
      "phone": "555-636-7000",
      "email": "bookings@krustyspin.example.com",
      "address1": "300 Krustylu Studios",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "notes": "DJ/MC, uplighting, montage video, photo booth, dance motivators. 120 min setup. Must feed staff. Balance due 7 days before event.",
      "milestones": [
        {
          "id": "m007",
          "title": "Balance due",
          "date": "2027-10-09",
          "notes": "7 days before event",
          "done": false
        },
        {
          "id": "m008",
          "title": "Montage photos due",
          "date": "2027-08-15",
          "notes": "Max 120 photos, 3 video clips",
          "done": false
        },
        {
          "id": "m009",
          "title": "Pre-event planning meeting",
          "date": "2027-09-01",
          "notes": "",
          "done": false
        }
      ],
      "contactName": "Krusty the Clown"
    },
    {
      "id": "v005",
      "name": "Bouvier Event Design",
      "type": "Party Planner",
      "status": "Deposit Paid",
      "contractAmt": "3750",
      "phone": "555-636-8000",
      "email": "marge@bouvier-events.example.com",
      "address1": "742 Evergreen Terrace",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "notes": "Event design and decor. 30 hrs consultation @ $125/hr. Balance due 30 days before event.",
      "milestones": [
        {
          "id": "m010",
          "title": "Decor concept approval",
          "date": "2027-08-01",
          "notes": "",
          "done": false
        },
        {
          "id": "m011",
          "title": "Balance due",
          "date": "2027-09-16",
          "notes": "30 days before event",
          "done": false
        }
      ],
      "contactName": "Marge Bouvier-Simpson"
    },
    {
      "id": "v006",
      "name": "Springfield Florist",
      "type": "Florist",
      "status": "Contacted",
      "contractAmt": "1200",
      "phone": "555-636-9000",
      "email": "agnes@springfieldflowers.example.com",
      "address1": "50 Petal Lane",
      "city": "Springfield",
      "stateProvince": "IL",
      "postalCode": "62701",
      "country": "United States",
      "notes": "Quote received for centerpieces and ceremony flowers. Contract not yet signed.",
      "milestones": [],
      "contactName": "Agnes Skinner"
    }
  ],
  "tasks": [
    {
      "id": "t001",
      "task": "Book venue for evening party",
      "category": "Venue",
      "priority": "High",
      "due": "2027-01-15",
      "done": true,
      "notes": ""
    },
    {
      "id": "t002",
      "task": "Book Temple Beth Springfield for service and luncheon",
      "category": "Venue",
      "priority": "High",
      "due": "2027-01-15",
      "done": true,
      "notes": ""
    },
    {
      "id": "t003",
      "task": "Hire photographer",
      "category": "Vendor",
      "priority": "High",
      "due": "2027-02-01",
      "done": true,
      "notes": ""
    },
    {
      "id": "t004",
      "task": "Hire DJ and entertainment",
      "category": "Vendor",
      "priority": "High",
      "due": "2027-02-01",
      "done": true,
      "notes": ""
    },
    {
      "id": "t005",
      "task": "Book event designer / party planner",
      "category": "Vendor",
      "priority": "High",
      "due": "2027-02-01",
      "done": true,
      "notes": ""
    },
    {
      "id": "t006",
      "task": "Send save-the-dates",
      "category": "Stationery",
      "priority": "High",
      "due": "2027-03-01",
      "done": true,
      "notes": ""
    },
    {
      "id": "t007",
      "task": "Order and mail invitations",
      "category": "Stationery",
      "priority": "High",
      "due": "2027-06-01",
      "done": true,
      "notes": "Mailed May 1, 2027"
    },
    {
      "id": "t008",
      "task": "Family meeting with Rabbi Krustofsky \u2014 service planning and Torah readers",
      "category": "Planning",
      "priority": "High",
      "due": "2027-04-16",
      "done": true,
      "notes": "6-month check-in completed"
    },
    {
      "id": "t009",
      "task": "Cantor session \u2014 4-month review",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-06-16",
      "done": false,
      "notes": ""
    },
    {
      "id": "t010",
      "task": "Cantor session \u2014 2-month check-in, bring d'var Torah draft",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-08-16",
      "done": false,
      "notes": ""
    },
    {
      "id": "t011",
      "task": "Final rehearsal at Temple Beth Springfield",
      "category": "Planning",
      "priority": "High",
      "due": "2027-10-09",
      "done": false,
      "notes": "4:00-6:00 PM full run-through"
    },
    {
      "id": "t012",
      "task": "Collect photos and videos for montage",
      "category": "Vendor",
      "priority": "Medium",
      "due": "2027-08-15",
      "done": false,
      "notes": "Max 120 photos, 3 video clips for DJ Krusty Spins"
    },
    {
      "id": "t013",
      "task": "Pre-event planning meeting with DJ Krusty Spins",
      "category": "Vendor",
      "priority": "Medium",
      "due": "2027-09-01",
      "done": false,
      "notes": "Timeline, music preferences, highlights"
    },
    {
      "id": "t014",
      "task": "Pay DJ Krusty Spins balance ($7,000)",
      "category": "Vendor",
      "priority": "High",
      "due": "2027-10-09",
      "done": false,
      "notes": "Due 7 days before event",
      "sourceId": "e009",
      "sourceCollection": "expenses"
    },
    {
      "id": "t015",
      "task": "Pay Temple Beth Springfield tuition balance ($500)",
      "category": "Vendor",
      "priority": "Medium",
      "due": "2027-07-01",
      "done": false,
      "notes": "",
      "sourceId": "e003",
      "sourceCollection": "expenses"
    },
    {
      "id": "t016",
      "task": "Pay Kiddush Sponsorship ($800)",
      "category": "Vendor",
      "priority": "Medium",
      "due": "2027-07-16",
      "done": false,
      "notes": "",
      "sourceId": "e004",
      "sourceCollection": "expenses"
    },
    {
      "id": "t017",
      "task": "Pay Shelbyville Snapshots second payment ($1,400)",
      "category": "Vendor",
      "priority": "High",
      "due": "2027-10-02",
      "done": false,
      "notes": "",
      "sourceId": "e006",
      "sourceCollection": "expenses"
    },
    {
      "id": "t018",
      "task": "Pay Bouvier Event Design balance ($1,875)",
      "category": "Vendor",
      "priority": "Medium",
      "due": "2027-09-16",
      "done": false,
      "notes": "",
      "sourceId": "e011",
      "sourceCollection": "expenses"
    },
    {
      "id": "t019",
      "task": "Create seating chart",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-10-02",
      "done": false,
      "notes": ""
    },
    {
      "id": "t020",
      "task": "Final guest count to Springfield Country Club",
      "category": "Catering",
      "priority": "High",
      "due": "2027-10-09",
      "done": false,
      "notes": "72 hours prior to event"
    },
    {
      "id": "t021",
      "task": "Send allergy and dietary restrictions to caterer",
      "category": "Catering",
      "priority": "High",
      "due": "2027-10-09",
      "done": false,
      "notes": "Ralph: peanut allergy. Lisa: vegetarian. Wendell: gluten free. Agnes: low sodium. Selma: shellfish."
    },
    {
      "id": "t022",
      "task": "Order kippot from Temple Sisterhood",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-08-01",
      "done": false,
      "notes": "Approx 40 needed"
    },
    {
      "id": "t023",
      "task": "Order party favors \u2014 donut sweatshirts",
      "category": "Theme",
      "priority": "Medium",
      "due": "2027-09-01",
      "done": false,
      "notes": "Allow 8 weeks lead time",
      "sourceId": "e013",
      "sourceCollection": "expenses"
    },
    {
      "id": "t024",
      "task": "Plan Friday night dinner \u2014 venue, menu, guest list",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-06-01",
      "done": false,
      "notes": "Out of towners, family, close friends"
    },
    {
      "id": "t025",
      "task": "Bart's outfit for service",
      "category": "Attire",
      "priority": "Medium",
      "due": "2027-09-01",
      "done": false,
      "notes": ""
    },
    {
      "id": "t026",
      "task": "Bart's outfit for evening party",
      "category": "Attire",
      "priority": "Medium",
      "due": "2027-09-01",
      "done": false,
      "notes": ""
    },
    {
      "id": "t027",
      "task": "Write parents speech",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-09-15",
      "done": false,
      "notes": ""
    },
    {
      "id": "t028",
      "task": "Prepare photo shot list for Shelbyville Snapshots",
      "category": "Vendor",
      "priority": "Medium",
      "due": "2027-09-15",
      "done": false,
      "notes": ""
    },
    {
      "id": "t029",
      "task": "Confirm all vendor details and contacts",
      "category": "Vendor",
      "priority": "High",
      "due": "2027-10-02",
      "done": false,
      "notes": ""
    },
    {
      "id": "t030",
      "task": "Notify family members of service roles \u2014 Torah readers, blessings",
      "category": "Planning",
      "priority": "Medium",
      "due": "2027-09-15",
      "done": false,
      "notes": ""
    },
    {
      "id": "t031",
      "task": "Negotiate florist quote \u2014 over budget by $200",
      "category": "Vendor",
      "priority": "Low",
      "due": "2027-08-01",
      "done": false,
      "notes": "Springfield Florist quoted $1,200 vs $1,000 budget"
    },
    {
      "id": "t032",
      "task": "Hair and makeup trial appointment \u2014 Marge",
      "category": "Attire",
      "priority": "Low",
      "due": "2027-09-01",
      "done": false,
      "notes": "",
      "sourceId": "e016",
      "sourceCollection": "expenses"
    },
    {
      "id": "t033",
      "task": "Follow up on missing RSVPs \u2014 Burns, Smithers, Jimbo, Richard",
      "category": "Planning",
      "priority": "High",
      "due": "2027-09-15",
      "done": false,
      "notes": "RSVP deadline Sep 15"
    },
    {
      "id": "t034",
      "task": "Get address for Dr. Nick Riviera and Richard",
      "category": "Planning",
      "priority": "Low",
      "due": "2027-08-01",
      "done": false,
      "notes": "Two guests have no address on file"
    },
    {
      "id": "t035",
      "task": "Schedule hair and makeup for Marge",
      "category": "Attire",
      "priority": "Medium",
      "due": "2027-08-01",
      "done": false,
      "notes": ""
    }
  ],
  "prep": [
    {
      "id": "pr001",
      "title": "Torah Portion Study",
      "status": "In Progress",
      "progress": 35,
      "targetDate": "2027-09-16",
      "notes": "Parshat Lech-Lecha. Working with tutor twice weekly. Homer keeps falling asleep during practice sessions."
    },
    {
      "id": "pr002",
      "title": "Haftarah Portion Study",
      "status": "In Progress",
      "progress": 20,
      "targetDate": "2027-09-16",
      "notes": "Starting to learn trope patterns. Making progress but easily distracted."
    },
    {
      "id": "pr003",
      "title": "D'var Torah Writing",
      "status": "Not Started",
      "progress": 0,
      "targetDate": "2027-08-16",
      "notes": "Draft due at 2-month cantor session. Bart wants to write about the importance of not wasting food."
    },
    {
      "id": "pr004",
      "title": "Service Prayers and Blessings",
      "status": "In Progress",
      "progress": 40,
      "targetDate": "2027-09-16",
      "notes": "Shacharit and Musaf blessings in progress. Kiddush blessing nearly memorized."
    },
    {
      "id": "pr005",
      "title": "Mitzvah Project \u2014 Acts of Hesed",
      "status": "In Progress",
      "progress": 15,
      "targetDate": "2027-08-01",
      "notes": "Decided to volunteer at Springfield Food Bank. Has completed 2 of 10 planned sessions."
    },
    {
      "id": "pr006",
      "title": "Thank You Speech",
      "status": "Not Started",
      "progress": 0,
      "targetDate": "2027-09-15",
      "notes": "Marge has requested that 'Eat my shorts' not appear in the speech."
    }
  ],
  "tables": [
    {
      "id": "tbl001",
      "name": "Table 1 \u2014 Evergreen",
      "capacity": 8,
      "type": "adult",
      "color": "#b8962e",
      "notes": "Head table \u2014 immediate family and officiant"
    },
    {
      "id": "tbl002",
      "name": "Table 2 \u2014 Springfield",
      "capacity": 10,
      "type": "adult",
      "color": "#3d5a80",
      "notes": "Family friends"
    },
    {
      "id": "tbl003",
      "name": "Table 3 \u2014 Shelbyville",
      "capacity": 12,
      "type": "adult",
      "color": "#3d7a5e",
      "notes": "Friends and coworkers"
    },
    {
      "id": "tbl004",
      "name": "Kids Table \u2014 Elementary",
      "capacity": 16,
      "type": "kids",
      "color": "#b06030",
      "notes": "Springfield Elementary crew"
    }
  ],
  "gifts": [
    {
      "id": "g001",
      "householdId": "h002",
      "fromName": "Ned Flanders",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 250,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": true,
      "thankYouMailed": true,
      "notes": "Came with a heartfelt diddily-card."
    },
    {
      "id": "g002",
      "householdId": "h006",
      "fromName": "Kirk Van Houten",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 180,
      "dateReceived": "2027-10-16",
      "attended": null,
      "thankYouWritten": true,
      "thankYouMailed": false,
      "notes": "Written, not yet mailed."
    },
    {
      "id": "g003",
      "householdId": "h008",
      "fromName": "Julius Hibbert",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 300,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": true,
      "thankYouMailed": true,
      "notes": "Came with a hearty chuckle."
    },
    {
      "id": "g004",
      "householdId": "h007",
      "fromName": "Clancy Wiggum",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Physical Gift",
      "description": "Custom police badge plaque \u2014 'Bart Simpson, Son of the Commandment'",
      "amount": null,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": true,
      "thankYouMailed": false,
      "notes": "Very thoughtful from Chief Wiggum."
    },
    {
      "id": "g005",
      "householdId": "h009",
      "fromName": "Carl Carlson",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 200,
      "dateReceived": "2027-10-17",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": ""
    },
    {
      "id": "g006",
      "householdId": "h003",
      "fromName": "Jacqueline Bouvier",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 500,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": true,
      "thankYouMailed": true,
      "notes": "Very generous from grandma."
    },
    {
      "id": "g007",
      "householdId": "h004",
      "fromName": "Patty & Selma Bouvier",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Physical Gift",
      "description": "Framed family photo collage \u2014 15 photos across the years",
      "amount": null,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": ""
    },
    {
      "id": "g008",
      "householdId": "h010",
      "fromName": "Timothy Lovejoy",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 150,
      "dateReceived": "2027-10-17",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": ""
    },
    {
      "id": "g009",
      "householdId": "h013",
      "fromName": "Seymour Skinner",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Physical Gift",
      "description": "Complete Encyclopedia Britannica set \u2014 24 volumes",
      "amount": null,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": "Very on-brand for Principal Skinner."
    },
    {
      "id": "g010",
      "householdId": "h012",
      "fromName": "Martin Prince Sr.",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Israel Bond",
      "description": "State of Israel Bond",
      "amount": 180,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": ""
    },
    {
      "id": "g011",
      "householdId": "h015",
      "fromName": "Gloria Muntz",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Cash",
      "amount": 50,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": "Ha-ha."
    },
    {
      "id": "g012",
      "householdId": "h005",
      "fromName": "Mr. and Mrs. Robert Terwilliger Sr.",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 200,
      "dateReceived": "2027-10-18",
      "attended": null,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": "Mailed from Shelbyville."
    },
    {
      "id": "g013",
      "householdId": "h006",
      "fromName": "Kirk Van Houten",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Personalized siddur with inscription",
      "amount": null,
      "dateReceived": "2027-10-16",
      "attended": null,
      "thankYouWritten": true,
      "thankYouMailed": true,
      "notes": "Beautiful inscription in Hebrew."
    },
    {
      "id": "g014",
      "householdId": "h013",
      "fromName": "Seymour Skinner",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Physical Gift",
      "description": "Barnes and Noble gift card",
      "amount": 50,
      "dateReceived": "2027-10-17",
      "attended": null,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": "Second gift \u2014 mailed after the event."
    },
    {
      "id": "g013",
      "householdId": "h006",
      "fromName": "Kirk Van Houten",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Cash / Check",
      "description": "Check",
      "amount": 150,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": ""
    },
    {
      "id": "g014",
      "householdId": "h013",
      "fromName": "Seymour Skinner",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Physical Gift",
      "description": "Custom engraved kippah",
      "amount": null,
      "dateReceived": "2027-10-16",
      "attended": true,
      "thankYouWritten": true,
      "thankYouMailed": false,
      "notes": "Engraved: 'B.S. Bar Mitzvah 2027'. Very thoughtful."
    },
    {
      "id": "g015",
      "householdId": "h009",
      "fromName": "Carl Carlson",
      "address1": "",
      "address2": "",
      "city": "",
      "stateProvince": "",
      "postalCode": "",
      "country": "",
      "giftType": "Gift Card",
      "description": "Amazon gift card",
      "amount": 100,
      "dateReceived": "2027-10-17",
      "attended": true,
      "thankYouWritten": false,
      "thankYouMailed": false,
      "notes": ""
    }
  ],
  "favors": [
    {
      "id": "fv001",
      "personId": "p003",
      "personName": "Bart Simpson",
      "size": "YM | Youth Medium",
      "printName": "The Bartman",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv002",
      "personId": "p004",
      "personName": "Lisa Simpson",
      "size": "YS | Youth Small",
      "printName": "Lisa",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv003",
      "personId": "p015",
      "personName": "Milhouse Van Houten",
      "size": "YS | Youth Small",
      "printName": "Milhouse",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv004",
      "personId": "p038",
      "personName": "Nelson Muntz",
      "size": "YM | Youth Medium",
      "printName": "Nelson",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv005",
      "personId": "p018",
      "personName": "Ralph Wiggum",
      "size": "YL | Youth Large",
      "printName": "Ralph",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv006",
      "personId": "p032",
      "personName": "Martin Prince Jr.",
      "size": "YS | Youth Small",
      "printName": "Martin",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv007",
      "personId": "p006",
      "personName": "Rod Flanders",
      "size": "YS | Youth Small",
      "printName": "Rod",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv008",
      "personId": "p007",
      "personName": "Todd Flanders",
      "size": "YS | Youth Small",
      "printName": "Todd",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv009",
      "personId": "p039",
      "personName": "Sherri Mackleberry",
      "size": "YS | Youth Small",
      "printName": "Sherri",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv010",
      "personId": "p040",
      "personName": "Terri Mackleberry",
      "size": "YS | Youth Small",
      "printName": "Terri",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv011",
      "personId": "p041",
      "personName": "Wendell Borton",
      "size": "YM | Youth Medium",
      "printName": "Wendell",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv012",
      "personId": "p042",
      "personName": "Database",
      "size": "YS | Youth Small",
      "printName": "Database",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv013",
      "personId": "p045",
      "personName": "Janey Powell",
      "size": "YS | Youth Small",
      "printName": "Janey",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv014",
      "personId": "p043",
      "personName": "Jimbo Jones",
      "size": "YM | Youth Medium",
      "printName": "Jimbo",
      "preprint": "TBD",
      "attending": "TBD",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv015",
      "personId": "p027",
      "personName": "Jessica Lovejoy",
      "size": "YS | Youth Small",
      "printName": "Jessica",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv016",
      "personId": "p021",
      "personName": "Janey Hibbert",
      "size": "YS | Youth Small",
      "printName": "Janey H",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv017",
      "personId": "p022",
      "personName": "Jules Hibbert",
      "size": "YM | Youth Medium",
      "printName": "Jules",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv018",
      "personId": "p001",
      "personName": "Homer Simpson",
      "size": "XXL | Adult XXL",
      "printName": "Homer",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv019",
      "personId": "p002",
      "personName": "Marge Simpson",
      "size": "AS | Adult Small",
      "printName": "Marge",
      "preprint": "Yes",
      "attending": "Yes",
      "notes": "",
      "category": ""
    },
    {
      "id": "fv020",
      "personId": null,
      "personName": "Richard",
      "size": "TBD",
      "printName": "Richard",
      "preprint": "TBD",
      "attending": "TBD",
      "notes": "",
      "category": ""
    }
  ],
  "ceremonyRoles": [
    {
      "section": "Torah Service",
      "role": "Aliyah 1 \u2014 Kohen",
      "assignee": "Jacqueline Bouvier",
      "hebrewName": "Yocheved bat Avraham v'Sarah",
      "notes": "Marge's mother \u2014 grandmother of Bar Mitzvah",
      "id": "cr_1775936049479_0",
      "sortOrder": 0
    },
    {
      "section": "Torah Service",
      "role": "Aliyah 2 \u2014 Levi",
      "assignee": "Robert Terwilliger Sr.",
      "hebrewName": "Reuven ben Moshe v'Rivka",
      "notes": "Family friend",
      "id": "cr_1775936049479_1",
      "sortOrder": 1
    },
    {
      "section": "Torah Service",
      "role": "Aliyah 3 \u2014 Parents",
      "assignee": "Homer and Marge Simpson",
      "hebrewName": "Chaim ben Avraham v'Sarah",
      "notes": "Parents of Bar Mitzvah",
      "id": "cr_1775936049479_2",
      "sortOrder": 2
    },
    {
      "section": "Torah Service",
      "role": "Aliyah 4 \u2014 Maftir",
      "assignee": "Bart Simpson",
      "hebrewName": "Baruch ben Chaim v'Miriam",
      "notes": "Bar Mitzvah",
      "id": "cr_1775936049480_3",
      "sortOrder": 3
    },
    {
      "section": "Torah Service",
      "role": "Hagbah (Lifting Torah)",
      "assignee": "Chief Clancy Wiggum",
      "hebrewName": "",
      "notes": "Has done it before \u2014 strong enough",
      "id": "cr_1775936049480_4",
      "sortOrder": 4
    },
    {
      "section": "Torah Service",
      "role": "Gelilah (Dressing Torah)",
      "assignee": "Ned Flanders",
      "hebrewName": "",
      "notes": "Family friend, experienced",
      "id": "cr_1775936049480_5",
      "sortOrder": 5
    },
    {
      "section": "Torah Service",
      "role": "Opening Ark",
      "assignee": "Patty Bouvier",
      "hebrewName": "",
      "notes": "Marge's sister",
      "id": "cr_1775936049480_6",
      "sortOrder": 6
    },
    {
      "section": "Torah Service",
      "role": "Returning Torah",
      "assignee": "Selma Bouvier",
      "hebrewName": "",
      "notes": "Marge's sister",
      "id": "cr_1775936049480_7",
      "sortOrder": 7
    },
    {
      "section": "English Readings",
      "role": "Prayer for Our Country",
      "assignee": "Mayor Joseph Quimby",
      "hebrewName": "",
      "notes": "",
      "id": "cr_1775936049480_8",
      "sortOrder": 8
    },
    {
      "section": "English Readings",
      "role": "Prayer for Israel",
      "assignee": "Rabbi Hyman Krustofsky",
      "hebrewName": "",
      "notes": "",
      "id": "cr_1775936049480_9",
      "sortOrder": 9
    },
    {
      "section": "English Readings",
      "role": "Prayer for Peace",
      "assignee": "Reverend Timothy Lovejoy",
      "hebrewName": "",
      "notes": "Interfaith \u2014 appropriate for non-Jewish family",
      "id": "cr_1775936049480_10",
      "sortOrder": 10
    },
    {
      "section": "Service Participation",
      "role": "Parental Blessing / Speech",
      "assignee": "Homer and Marge Simpson",
      "hebrewName": "",
      "notes": "Keep it under 150 words, Homer",
      "id": "cr_1775936049480_11",
      "sortOrder": 11
    },
    {
      "section": "Service Participation",
      "role": "Ushers",
      "assignee": "Lenny Powell and Carl Carlson",
      "hebrewName": "",
      "notes": "Homer's friends from the plant",
      "id": "cr_1775936049480_12",
      "sortOrder": 12
    },
    {
      "section": "Service Participation",
      "role": "Friday Evening Service",
      "assignee": "",
      "hebrewName": "",
      "notes": "Yes \u2014 Homer, Marge, Lisa, and Maggie attending",
      "id": "cr_1775936049480_13",
      "sortOrder": 13
    },
    {
      "section": "Service Participation",
      "role": "Morning Minyan",
      "assignee": "",
      "hebrewName": "",
      "notes": "Thursday \u2014 Homer confirmed",
      "id": "cr_1775936049480_14",
      "sortOrder": 14
    }
  ],
  "quickNotes": "Demo event \u2014 Bart Simpson's Bar Mitzvah. All data is fictional. Simpsons characters throughout.\n\nKey dietary notes:\n- Ralph Wiggum: SEVERE peanut allergy \u2014 alert caterer\n- Lisa Simpson: vegetarian\n- Wendell Borton: gluten free\n- Ned, Rod, Todd Flanders: kosher\n- Rabbi Krustofsky: strictly kosher\n- Agnes Skinner: low sodium\n- Selma Bouvier: shellfish allergy",
  "dayOf": {
    "checklist": [
      {
        "id": "doi001",
        "task": "Confirm photographer arrival time with Shelbyville Snapshots",
        "timeBlock": "Morning",
        "done": false
      },
      {
        "id": "doi002",
        "task": "Pick up kippot from Temple Sisterhood",
        "timeBlock": "Morning",
        "done": false
      },
      {
        "id": "doi003",
        "task": "Tallit and yarmulke pressed and ready for Bart",
        "timeBlock": "Morning",
        "done": false
      },
      {
        "id": "doi004",
        "task": "Alert caterer: Ralph Wiggum has severe peanut allergy",
        "timeBlock": "Morning",
        "done": false
      },
      {
        "id": "doi005",
        "task": "Confirm DJ setup access time with Springfield Country Club",
        "timeBlock": "Afternoon",
        "done": false
      },
      {
        "id": "doi006",
        "task": "Deliver place cards and table assignments to Springfield Country Club",
        "timeBlock": "Afternoon",
        "done": false
      },
      {
        "id": "doi007",
        "task": "Final headcount confirmed with caterer",
        "timeBlock": "Afternoon",
        "done": false
      },
      {
        "id": "doi008",
        "task": "Ensure kosher meals are clearly labeled and separated",
        "timeBlock": "Afternoon",
        "done": false
      }
    ]
  }
};

// Convert a flat array of records into V3 schema rows: { id, event_id, data, ...indexed }
function toRows(eventId, records, indexedFields = []) {
  return records.map(r => {
    const row = {
      id:         r.id,
      event_id:   eventId,
      data:       r,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
    // Copy indexed fields to top-level columns
    for (const field of indexedFields) {
      if (r[field] !== undefined) row[field] = r[field];
    }
    return row;
  });
}

export default async function handler(req, res) {
  const authHeader = req.headers.authorization || "";
  const token      = authHeader.replace("Bearer ", "");
  const isCron     = req.headers["x-vercel-cron"] === "1";

  if (req.method !== "GET" && req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  if (!isCron && token !== process.env.ADMIN_RESET_TOKEN) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  const supabase = createClient(
    process.env.VITE_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false } }
  );

  try {
    // 1. Find or create the demo system user
    const { data: { users }, error: listErr } = await supabase.auth.admin.listUsers();
    if (listErr) throw new Error("Could not list users: " + listErr.message);

    let demoUser = users.find(u => u.email === DEMO_USER_EMAIL);
    if (!demoUser) {
      const { data: created, error: createErr } = await supabase.auth.admin.createUser({
        email:         DEMO_USER_EMAIL,
        email_confirm: true,
        user_metadata: { name: "SimchaKit Demo" },
      });
      if (createErr) throw new Error("Could not create demo user: " + createErr.message);
      demoUser = created.user;
    }

    // 2. Upsert the demo event row
    const { error: eventErr } = await supabase.from("events").upsert({
      id:           DEMO_EVENT_ID,
      owner_id:     demoUser.id,
      name:         SEED.adminConfig.name,
      type:         SEED.adminConfig.type,
      admin_config: SEED.adminConfig,
      quick_notes:  SEED.quickNotes || "",
      archived:     false,
      updated_at:   new Date().toISOString(),
    }, { onConflict: "id" });
    if (eventErr) throw new Error("Could not upsert event: " + eventErr.message);

    // 3. Delete all existing collection data for demo event
    for (const col of COLLECTIONS) {
      const { error } = await supabase.from(col).delete().eq("event_id", DEMO_EVENT_ID);
      if (error) console.warn(`[reset-demo] Could not clear ${col}: ${error.message}`);
    }

    // 4. Re-insert seed data using V3 schema: { id, event_id, data: jsonb }
    const inserts = [
      { table: "households",     rows: toRows(DEMO_EVENT_ID, SEED.households,    ["status"]).map(r => ({ ...r, group_name: r.data.group, out_of_town: r.data.outOfTown || false })) },
      { table: "people",         rows: toRows(DEMO_EVENT_ID, SEED.people)         },
      { table: "expenses",       rows: toRows(DEMO_EVENT_ID, SEED.expenses)       },
      { table: "vendors",        rows: toRows(DEMO_EVENT_ID, SEED.vendors)        },
      { table: "tasks",          rows: toRows(DEMO_EVENT_ID, SEED.tasks)          },
      { table: "prep",           rows: toRows(DEMO_EVENT_ID, SEED.prep)           },
      { table: "tables",         rows: toRows(DEMO_EVENT_ID, SEED.tables)         },
      { table: "gifts",          rows: toRows(DEMO_EVENT_ID, SEED.gifts)          },
      { table: "favors",         rows: toRows(DEMO_EVENT_ID, SEED.favors)         },
      { table: "ceremony_roles", rows: toRows(DEMO_EVENT_ID, SEED.ceremonyRoles)  },
    ];

    for (const { table, rows } of inserts) {
      if (!rows || rows.length === 0) continue;
      const { error } = await supabase.from(table).insert(rows);
      if (error) throw new Error(`Failed to insert ${table}: ${error.message}`);
    }

    // 5. Upsert dayOf as single document
    if (SEED.dayOf) {
      const { error } = await supabase.from("dayof").upsert({
        event_id:   DEMO_EVENT_ID,
        data:       SEED.dayOf,
        updated_at: new Date().toISOString(),
      }, { onConflict: "event_id" });
      if (error) console.warn("[reset-demo] Could not upsert dayof:", error.message);
    }

    console.log(`[reset-demo] Reset complete at ${new Date().toISOString()}`);
    return res.status(200).json({
      ok:        true,
      message:   "Demo event reset successfully",
      eventId:   DEMO_EVENT_ID,
      timestamp: new Date().toISOString(),
    });

  } catch (err) {
    console.error("[reset-demo] Error:", err.message);
    return res.status(500).json({ error: err.message });
  }
}
