// ─────────────────────────────────────────────────────────────────────────────
// SimchaKit V3 — api/send-invite.js
// Vercel serverless function.
// POST { eventId, inviteeEmail, role, eventName, userId, message }
// Creates an invitation record and sends the invite email via Brevo.
// Inviter name is resolved server-side from user_profiles.
//
// Flow:
//   1. Validate request body
//   2. Verify the requesting user is an owner or editor of the event
//      — Owners can invite any role (editor, viewer, coordinator)
//      — Editors can invite viewers or coordinators only (not editors)
//      — Viewers and coordinators cannot invite
//   3. Enforce collaborator cap (max 5 accepted collaborators per event)
//   4. Reject if the invitee is already an accepted collaborator on this event
//   5. Insert row into event_invitations (token auto-generated by Postgres)
//   6. Send Brevo transactional invite email (Template 19)
//   7. Return { sent: true, invitationId }
//
// For link-only invites (no inviteeEmail), omit inviteeEmail from the request.
// The function will insert the invitation row and return the invite URL
// without sending an email. The app displays the URL for the owner to copy.
//
// Error codes returned to the app:
//   NOT_AUTHORIZED      — userId is not an owner or editor of this event
//   ESCALATION_DENIED   — editor attempted to invite an editor (privilege escalation)
//   CAP_REACHED         — event has 5 accepted collaborators (the maximum)
//   ALREADY_COLLABORATOR — inviteeEmail is already an accepted collaborator
//   INVALID_ROLE        — role is not "editor", "viewer", or "coordinator"
//
// Brevo transactional API: POST https://api.brevo.com/v3/smtp/email
// Collaborator Invite Email template ID: 19
// ─────────────────────────────────────────────────────────────────────────────

const BREVO_TRANSACTIONAL_URL     = "https://api.brevo.com/v3/smtp/email";
const INVITE_TEMPLATE_ID          = 19;
const COLLABORATOR_CAP            = 5;
const INVITE_BASE_URL             = "https://app.simcha-kit.com/invite";
const VALID_ROLES                 = ["editor", "viewer", "coordinator"];

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const BREVO_API_KEY = process.env.BREVO_API_KEY;
  if (!BREVO_API_KEY) {
    console.error("[SimchaKit] send-invite: BREVO_API_KEY is not set.");
    return res.status(500).json({ error: "Server configuration error." });
  }

  const {
    eventId,
    inviteeEmail,
    role,
    eventName,
    userId,
    message,
  } = req.body || {};

  // ── Validate required fields ─────────────────────────────────────────────────
  if (!eventId || typeof eventId !== "string") {
    return res.status(400).json({ error: "Missing or invalid eventId." });
  }
  if (!userId || typeof userId !== "string") {
    return res.status(400).json({ error: "Missing or invalid userId." });
  }
  if (!role || !VALID_ROLES.includes(role)) {
    return res.status(400).json({ error: "INVALID_ROLE" });
  }
  if (!eventName || typeof eventName !== "string") {
    return res.status(400).json({ error: "Missing eventName." });
  }

  // inviteeEmail is optional (link-only invite if omitted)
  const isEmailInvite = !!inviteeEmail;
  if (isEmailInvite && typeof inviteeEmail !== "string") {
    return res.status(400).json({ error: "Invalid inviteeEmail." });
  }

  // ── Supabase client (service role) ──────────────────────────────────────────
  const { createClient } = await import("@supabase/supabase-js");
  const supabase = createClient(
    process.env.VITE_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
  );

  // ── Step 1: Verify requesting user is an owner or editor ──────────────────
  const { data: event, error: eventError } = await supabase
    .from("events")
    .select("id, owner_id")
    .eq("id", eventId)
    .single();

  if (eventError || !event) {
    return res.status(404).json({ error: "Event not found." });
  }

  const isOwner = event.owner_id === userId;
  let isEditor = false;

  if (!isOwner) {
    // Check if caller is an editor on this event
    const { data: collabRow } = await supabase
      .from("event_collaborators")
      .select("role")
      .eq("event_id", eventId)
      .eq("user_id", userId)
      .not("accepted_at", "is", null)
      .maybeSingle();

    if (collabRow?.role === "editor") {
      isEditor = true;
    } else {
      return res.status(403).json({ error: "NOT_AUTHORIZED" });
    }
  }

  // Editors cannot invite other editors (privilege escalation)
  if (isEditor && role === "editor") {
    return res.status(403).json({ error: "ESCALATION_DENIED" });
  }

  // ── Step 2: Enforce collaborator cap ─────────────────────────────────────────
  // Ritual Coordinators do not count against the family's cap and are
  // never blocked by it, so they are excluded from the count and the cap check is
  // skipped entirely for coordinator invites.
  if (role !== "coordinator") {
    const { count, error: countError } = await supabase
      .from("event_collaborators")
      .select("id", { count: "exact", head: true })
      .eq("event_id", eventId)
      .neq("role", "coordinator")
      .not("accepted_at", "is", null);

    if (countError) {
      console.error("[SimchaKit] send-invite: collaborator count failed:", countError.message);
      return res.status(500).json({ error: "Failed to validate collaborator count." });
    }
    if (count >= COLLABORATOR_CAP) {
      return res.status(403).json({ error: "CAP_REACHED" });
    }
  }

  // ── Step 3: Reject if invitee is already an accepted collaborator ─────────────
  // Only applies to email invites — link invites cannot pre-check by email.
  // Uses user_profiles (application data layer) rather than auth.admin API,
  // consistent with the pattern in notify.js and brevo-sync.js.
  if (isEmailInvite) {
    const { data: existingProfile } = await supabase
      .from("user_profiles")
      .select("id")
      .eq("email", inviteeEmail.trim().toLowerCase())
      .maybeSingle();

    if (existingProfile?.id) {
      const { data: existingCollab } = await supabase
        .from("event_collaborators")
        .select("id")
        .eq("event_id", eventId)
        .eq("user_id", existingProfile.id)
        .not("accepted_at", "is", null)
        .maybeSingle();

      if (existingCollab) {
        return res.status(409).json({ error: "ALREADY_COLLABORATOR" });
      }
    }
  }

  // ── Step 4: Insert invitation row ────────────────────────────────────────────
  // Resolve owner display_name and email from user_profiles.
  // These are stored on the invitation so accept-invite.js can read them
  // without a second lookup, and so the invitee sees the owner's name in the email.
  let inviterEmail = null;
  let inviterName  = null;
  const { data: inviterProfile } = await supabase
    .from("user_profiles")
    .select("email, display_name")
    .eq("id", userId)
    .maybeSingle();
  inviterEmail = inviterProfile?.email || null;
  // Use display_name if set; fall back to email prefix; never use "the event owner"
  if (inviterProfile?.display_name) {
    inviterName = inviterProfile.display_name;
  } else if (inviterEmail) {
    inviterName = inviterEmail.split("@")[0];
  } else {
    inviterName = "Someone";
  }

  // token and expires_at are generated by Postgres defaults.
  const { data: invitation, error: insertError } = await supabase
    .from("event_invitations")
    .insert({
      event_id:          eventId,
      invited_by:        userId,
      invited_by_email:  inviterEmail,
      invited_by_name:   inviterName,
      email:             isEmailInvite ? inviteeEmail : null,
      role,
    })
    .select("id, token")
    .single();

  if (insertError || !invitation) {
    console.error("[SimchaKit] send-invite: invitation insert failed:", insertError?.message);
    return res.status(500).json({ error: "Failed to create invitation." });
  }

  const inviteUrl = `${INVITE_BASE_URL}/${invitation.token}`;

  // ── Step 5: Send invite email (email invites only) ───────────────────────────
  if (isEmailInvite) {
    try {
      const roleLabel =
        role === "editor"      ? "co-plan" :
        role === "coordinator" ? "help with the ceremony for" :
                                 "follow along on";

      const transactionalPayload = {
        to: [{ email: inviteeEmail }],
        templateId: INVITE_TEMPLATE_ID,
        params: {
          INVITER_NAME: inviterName,
          EVENT_NAME:   eventName,
          ROLE_LABEL:   roleLabel,
          INVITE_URL:   inviteUrl,
          MESSAGE:      message || "",
        },
      };

      const brevoHeaders = {
        "accept":       "application/json",
        "content-type": "application/json",
        "api-key":      BREVO_API_KEY,
      };

      const brevoResponse = await fetch(BREVO_TRANSACTIONAL_URL, {
        method:  "POST",
        headers: brevoHeaders,
        body:    JSON.stringify(transactionalPayload),
      });

      if (brevoResponse.status !== 201) {
        const errorBody = await brevoResponse.text();
        console.error(`[SimchaKit] send-invite: Brevo email failed (${brevoResponse.status}):`, errorBody);
        // Non-fatal — invitation row was created. Return success with a warning.
        return res.status(200).json({
          sent:         false,
          invitationId: invitation.id,
          inviteUrl,
          warning:      "Invitation created but email delivery failed. Share the invite link manually.",
        });
      }
    } catch (brevoErr) {
      console.error("[SimchaKit] send-invite: Brevo email error:", brevoErr.message);
      return res.status(200).json({
        sent:         false,
        invitationId: invitation.id,
        inviteUrl,
        warning:      "Invitation created but email delivery failed. Share the invite link manually.",
      });
    }
  }

  // ── Step 6: Return success ───────────────────────────────────────────────────
  return res.status(200).json({
    sent:         isEmailInvite,
    invitationId: invitation.id,
    inviteUrl,
  });
}
